# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[󰃛](bold green)[󰃛](yellow)[󰃛](red)[󰃛](purple)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

error_symbol = "[✗](bold red) "
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true





[git_branch]
symbol = "🌱 "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"


[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_format = "%T"



[username]
style_user = "white bold"
style_root = "black bold"
format = "|[$user]($style) "
disabled = false
show_always = true











