#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.screenlayout/display.sh
bash -c "sleep 2s;$HOME/.config/polybar/launch.sh" &
#picom -b -f  &
compton -b & 
nitrogen --set-scaled --random &
~/.scripts/wall_change &
#conky -d &
#lxappearance &
#bash -c "sleep 10s;exec /usr/bin/apt-notifier" &
#usb-unmounter-start &
#bash -c "sleep 9s;stalonetray -t" &
#bash -c "sleep 7s;tint2 -c $HOME/.config/tint2/tint2rcappsonly.tint2rc" &
#bash -c "sleep 5s;tint2 -c tint2 -c $HOME/.config/tint2/tint2rcsystrayonly.tint2rc" &
#swallow
#pgrep bspswallow || bspswallow &
#sudo pkill mpd
#mpd
ntfd &
~/.scripts/conkystart &
urxvtd -f -o &
#~/.local/bin/mp-daemon &
emacs --daemon &
xmodmap ~/.Xmodmap &

bspc monitor -d I II III IV V VI VII VIII
bspc config border_width         2
bspc config window_gap			 8
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config wm_name LG3D

bspc rule -a Firefox  desktop='^2'
bspc rule -a mpv      desktop='^6'
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a Chromium-devel desktop='^3'
bspc rule -a Emacs    state=tiled
bspc rule -a Emacs    desktop='^1'
#bspc rule -a Zathura desktop='^2'
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off

#/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
/usr/bin/lxpolkit &
wmname LG3D &
# border colors 
bspc config focused_border_color "#4B7CFF"
bspc config normal_border_color "#FF1C83"
